sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      env: NODE_VERSION="4"
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: NODE_VERSION="4"

    - os: linux
      compiler: gcc
      dist: trusty
      env: NODE_VERSION="6"
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: NODE_VERSION="6"

    - os: linux
      compiler: gcc
      dist: trusty
      env: NODE_VERSION="7"
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: NODE_VERSION="7"

    - os: linux
      compiler: gcc
      dist: trusty
      env: NODE_VERSION="8"
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: NODE_VERSION="8"
  
branches:
#  only:
#    - master

git:
  depth: 10

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-6']

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install

before_script:
  - env
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-6" CC="gcc-6" && cmake .; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then export npm_config_clang=1 && cmake .;     fi

script:
  - npm test
  - cmake --build .
  - ctest -VV
